[package]
name = "Cube"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra-glm = "0.18.0"
minifb = "0.26.0"
rand = "0.8.5"
once_cell = "1.19.0"
image = { version = "0.24", default-features = false, features = ["exr", "jpeg"] }
rayon = "1.11.0"
